// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfMhDY-BknY69y_e-8xmRlV7Ne1eRPC5U',
    appId: '1:986164280260:web:91cb4aed81b58a144c0291',
    messagingSenderId: '986164280260',
    projectId: 'projectaftervaccation',
    authDomain: 'projectaftervaccation.firebaseapp.com',
    storageBucket: 'projectaftervaccation.firebasestorage.app',
    measurementId: 'G-Z1K4XRPTET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHVug7Ly7X96VRjGcL2NGv_t54ZnSRdQI',
    appId: '1:986164280260:android:f179f9846f7991764c0291',
    messagingSenderId: '986164280260',
    projectId: 'projectaftervaccation',
    storageBucket: 'projectaftervaccation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKK_EU0rga6ISb3HiHv2ZTx5yIblNsD0M',
    appId: '1:986164280260:ios:afee9b79298141304c0291',
    messagingSenderId: '986164280260',
    projectId: 'projectaftervaccation',
    storageBucket: 'projectaftervaccation.firebasestorage.app',
    iosBundleId: 'com.example.newprojectfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKK_EU0rga6ISb3HiHv2ZTx5yIblNsD0M',
    appId: '1:986164280260:ios:afee9b79298141304c0291',
    messagingSenderId: '986164280260',
    projectId: 'projectaftervaccation',
    storageBucket: 'projectaftervaccation.firebasestorage.app',
    iosBundleId: 'com.example.newprojectfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfMhDY-BknY69y_e-8xmRlV7Ne1eRPC5U',
    appId: '1:986164280260:web:1113c4d29fd78bed4c0291',
    messagingSenderId: '986164280260',
    projectId: 'projectaftervaccation',
    authDomain: 'projectaftervaccation.firebaseapp.com',
    storageBucket: 'projectaftervaccation.firebasestorage.app',
    measurementId: 'G-WNC3VEJNEW',
  );
}
